#!/usr/bin/env python3
"""Regenerate hpc/thermal_hpc.py from the notebook.

The HPC sweep must run the SAME physics as the notebook, so the library is not
hand-written: it is EXTRACTED, verbatim, from the notebook's own cells.  Edit the
notebook, re-run this, and the cluster code follows.  Nothing here is a
paraphrase of a notebook function -- if a name is in WANTED below, its source is
copied character for character.

    python hpc/build_thermal_hpc.py [--notebook Schwinger_Thermal_State_W10.ipynb]
"""
import argparse
import ast
import io
import json
import pathlib
import sys

# Top-level names to lift out of the notebook, in the order they must appear.
# (cell id, [names]) -- cell ids, not indices, so inserting cells cannot break this.
WANTED = [
    ("a1d1540d", ["get_schwinger_hamiltonian"]),
    ("88c6ac34", ["O_n"]),
    ("66db747e", ["L_n"]),
    ("18791525", ["D_matrix"]),
    ("a7c8450b", ["diagonalized_lindblad_ops"]),
    ("37fd9c70", ["_basis_bits", "_sqrtm_psd", "uhlmann_fidelity"]),
    ("1790bf54", ["sector_indices", "sector_ops", "staggered_bitstring",
                  "gibbs_sector", "fidelity_to", "lindblad_rhs", "rk4_dt",
                  "_rk4_stepper", "basis_rho", "exact_fidelity_curve",
                  "t_at_fidelity", "fit_scaling"]),
]

HEADER = '''"""Schwinger-model thermal-state relaxation: the cluster-side library.

AUTO-GENERATED by hpc/build_thermal_hpc.py from {nb}.
DO NOT EDIT -- edit the notebook cell and regenerate, or the cluster will quietly
stop computing what the notebook says it computes.

Contains only what the exact sector-Lindblad relaxation sweep needs, so importing
it pulls in qiskit + scipy but NOT qiskit-aer, matplotlib, or qiskit-ibm-runtime.
"""
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
from qiskit.quantum_info import SparsePauliOp

'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--notebook", default="Schwinger_Thermal_State_W10.ipynb")
    ap.add_argument("--out", default="hpc/thermal_hpc.py")
    args = ap.parse_args()

    nb = json.load(io.open(args.notebook, encoding="utf-8"))
    cells = {c.get("id"): "".join(c["source"]) for c in nb["cells"]
             if c["cell_type"] == "code"}

    chunks = [HEADER.format(nb=args.notebook)]
    for cid, names in WANTED:
        if cid not in cells:
            sys.exit(f"cell id {cid!r} is gone from {args.notebook}; "
                     f"fix WANTED in {__file__}")
        src = cells[cid]
        tree = ast.parse(src)
        found = {n.name: n for n in tree.body
                 if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef,
                                   ast.ClassDef))}
        for name in names:
            if name not in found:
                sys.exit(f"{name!r} not found in cell {cid!r}")
            node = found[name]
            # include any decorators / comments directly above the def
            seg = ast.get_source_segment(src, node)
            chunks.append(seg.rstrip() + "\n\n\n")

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    text = "".join(chunks).rstrip() + "\n"
    out.write_text(text, encoding="utf-8")

    # a generated file that does not import is worse than no generated file
    compile(text, str(out), "exec")
    n_defs = sum(len(n) for _, n in WANTED)
    print(f"wrote {out}  ({n_defs} definitions, {len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
