"""Schwinger-model thermal-state relaxation: the cluster-side library.

AUTO-GENERATED by hpc/build_thermal_hpc.py from Schwinger_Thermal_State_W10.ipynb.
DO NOT EDIT -- edit the notebook cell and regenerate, or the cluster will quietly
stop computing what the notebook says it computes.

Contains only what the exact sector-Lindblad relaxation sweep needs, so importing
it pulls in qiskit + scipy but NOT qiskit-aer, matplotlib, or qiskit-ibm-runtime.
"""
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
from qiskit.quantum_info import SparsePauliOp

def get_schwinger_hamiltonian(L: int, m: float, e: float, a: float, include_shifts: bool = True) -> SparsePauliOp:
    if L <= 0:
        raise ValueError("L must be >= 1.")
    if a == 0:
        raise ValueError("a must be nonzero.")
    
    terms = []

    # Kinetic term
    ## H_kin = sum_{i=0}^{L-2} (1/(4a)) (X_i X_{i+1} + Y_i Y_{i+1})
    kin_coeff = 1.0 / (4.0 * a)
    for i in range(L - 1):
        terms.append(("XX", [i, i + 1], kin_coeff))
        terms.append(("YY", [i, i + 1], kin_coeff))

    # Mass term
    ## H_mass = sum_i m * (-1)^i * (Z_i + I)/(2a)
    for i in range(L):
        coeff = m * ((-1) ** i) / (2.0 * a)
        terms.append(("Z", [i], coeff))
        if include_shifts: # global energy shift
            terms.append(("I", [0], coeff))

    # Electric term
    ## E_i = (e/2) (S_i + C_i),  S_i = sum_{j<i} Z_j,  C_i = sum_{j<i} (-1)^j
    ## E_i^2 = (e^2/4) [ S_i^2 + 2 C_i S_i + C_i^2 ]
    ## S_i^2 = i*I + 2 sum_{j<k<i} Z_j Z_k
    base_I = (a / 2.0) * (e**2 / 4.0)
    zz_coeff = (a * e**2) / 4.0
    z_per_link_unit = (a * e**2) / 4.0

    for i in range(1, L + 1):
        # C_i = sum_{j=0}^{i-1} (-1)^j = 1 if i is odd else 0
        C = i % 2

        # Identity from i*I + C^2*I
        if include_shifts:
            terms.append(("I", [0], base_I * (i + C))) # since C^2 = C for C in {0, 1}

        # linear Z terms: (a/2)*(e^2/4)*(2 C) * sum_{j<i} Z_j = (a e^2/4)*C * sum_{j<i} Z_j
        if C == 1:
            for j in range(i):
                terms.append(("Z", [j], z_per_link_unit))

        # ZZ terms: (a/2)*(e^2/4)*(2) * sum_{j<k<i} Z_j Z_k = (a e^2/4) * sum_{j<k<i} Z_j Z_k
        for j in range(i):
            for k in range(j + 1, i):
                terms.append(("ZZ", [j, k], zz_coeff))

    H = SparsePauliOp.from_sparse_list(terms, num_qubits = L)
    return H.simplify()


def O_n(n: int, L: int, a: float) -> SparsePauliOp:
    """
    n: site
    L: number of sites
    """
    s = (-1)**n

    I_label = "I" * L

    chars = ["I"] * L
    chars[-1 - n] = "Z" # rightmost is qubit 0
    Z_label = "".join(chars)

    O = SparsePauliOp.from_list([
        (I_label, s/(2.0*a)),
        (Z_label, s/(2.0*a)),
    ])

    return O.simplify()


def L_n(n: int, H: SparsePauliOp, L: int, a: float, T: float) -> SparsePauliOp:
    O = O_n(n, L, a)
    comm = H @ O - O @ H

    return (O - (1.0/(4.0*T)) * comm).simplify()


def D_matrix(L: int, a: float, kind: str, D0: float, sigma: float | None = None):
    D = np.zeros((L, L), dtype = float)
    for n1 in range(L):
        for n2 in range(L):
            x = (n1 - n2) * a
            if kind == "delta":
                D[n1, n2] = D0 if n1 == n2 else 0.0
            elif kind == "gaussian":
                assert sigma is not None
                D[n1, n2] = D0 * np.exp(-(x*x) / (2.0*sigma*sigma))
            elif kind == "const":
                D[n1, n2] = D0
            else:
                raise ValueError("kind must be delta/gaussian/const")
    return D


def diagonalized_lindblad_ops(
    raw_L_ops: list[SparsePauliOp],
    D: np.ndarray,
    a_lat: float,
    tol: float = 1e-12,
) -> list[SparsePauliOp]:
    """
    Convert correlated dissipator

        a^2 sum_{n1,n2} D[n1,n2]
        ( L[n2] rho L[n1]^dag - 1/2 {L[n1]^dag L[n2], rho} )

    into diagonal Lindblad form

        sum_alpha ( L_eff[alpha] rho L_eff[alpha]^dag
        - 1/2 {L_eff[alpha]^dag L_eff[alpha], rho} ).
    """
    D = np.asarray(D, dtype=complex)

    if D.shape != (len(raw_L_ops), len(raw_L_ops)):
        raise ValueError("D must have shape (len(raw_L_ops), len(raw_L_ops))")

    # D should be Hermitian positive semidefinite
    if not np.allclose(D, D.conj().T, atol=1e-10):
        raise ValueError("D must be Hermitian for Lindblad diagonalization")

    evals, evecs = np.linalg.eigh(D)

    eff_ops = []

    for alpha, lam in enumerate(evals):
        if lam < -tol:
            raise ValueError(f"D has negative eigenvalue {lam}; not completely positive")

        if lam <= tol:
            continue

        coeff = a_lat * np.sqrt(lam)

        # eigenvector column alpha: evecs[n, alpha]
        Lop_eff = None

        for n, Lop_n in enumerate(raw_L_ops):
            c = coeff * np.conj(evecs[n, alpha])

            if abs(c) <= tol:
                continue

            term = c * Lop_n

            if Lop_eff is None:
                Lop_eff = term
            else:
                Lop_eff = Lop_eff + term

        if Lop_eff is not None:
            eff_ops.append(Lop_eff.simplify())

    return eff_ops


def _basis_bits(init_state, n):
    """Computational-basis state -> bit list with bits[q] = qubit q.

    Matches qiskit's initialize(label) convention: the RIGHTMOST character of a
    bitstring is qubit 0. Accepts a bitstring (e.g. "0101") or an int.
    """
    if isinstance(init_state, str):
        return [int(b) for b in reversed(init_state)]
    if isinstance(init_state, (int, np.integer)):
        return [(int(init_state) >> i) & 1 for i in range(n)]
    raise TypeError("init_state must be a bitstring or int (basis state).")


def _sqrtm_psd(A):
    """Matrix square root of a Hermitian positive-semidefinite matrix."""
    w, v = np.linalg.eigh(np.asarray(A, dtype=complex))
    return (v * np.sqrt(np.clip(w.real, 0.0, None))) @ v.conj().T


def uhlmann_fidelity(rho, sigma):
    """F(rho, sigma) = Tr sqrt( rho^{1/2} sigma rho^{1/2} ),  in [0, 1]; 1 iff equal.

    Evaluated as the nuclear norm (sum of singular values) || rho^{1/2} sigma^{1/2} ||_1,
    which is the same quantity but stays stable for the RANK-DEFICIENT states here:
    the sector-restricted Gibbs state is singular on the full Hilbert space, so a
    naive sqrtm of the triple product is badly conditioned.

    Convention: this is the SQUARE ROOT of qiskit's state_fidelity(), which returns F**2.
    """
    M = _sqrtm_psd(rho) @ _sqrtm_psd(sigma)
    return float(np.clip(np.linalg.svd(M, compute_uv=False).sum(), 0.0, 1.0))


def sector_indices(L: int, Q0: int = 0) -> np.ndarray:
    """Computational-basis indices with total charge Sz = (#0) - (#1) = Q0."""
    return np.array([i for i in range(2 ** L)
                     if L - 2 * bin(i).count("1") == Q0], dtype=int)


def sector_ops(L, m, e, a, T, D_kind="delta", D0=1.0, D_sigma=None, Q0=0):
    """(H, effective jump operators) at size L, restricted to the Sz = Q0 block.

    Exactly the construction used everywhere else in this notebook --
    get_schwinger_hamiltonian -> L_n -> D_matrix -> diagonalized_lindblad_ops -- with
    the rows and columns outside the sector dropped at the very end. The truncation is
    lossless because H and the L(n) are block diagonal in Sz.

    Returns (H_sec, [L_sec], idx) as scipy CSR matrices, plus the index list mapping
    sector positions back to full-Hilbert basis states.
    """
    H = get_schwinger_hamiltonian(L, m, e, a)
    raw = [L_n(n=n, H=H, L=L, a=a, T=T) for n in range(L)]
    D = D_matrix(L, a, kind=D_kind, D0=D0, sigma=D_sigma)
    eff = diagonalized_lindblad_ops(raw, D, a)

    idx = sector_indices(L, Q0)
    cut = lambda op: op.to_matrix(sparse=True).tocsr()[idx][:, idx].tocsr()
    return cut(H), [cut(x) for x in eff], idx


def staggered_bitstring(L: int) -> str:
    """|0101...>, the half-filling reference state (Sz = 0). Rightmost char = qubit 0."""
    return "01" * (L // 2) if L % 2 == 0 else "0" + "10" * (L // 2)


def gibbs_sector(H_sec, T):
    """e^{-H/T}/Z built directly in the sector -- the target the dynamics can reach.

    Same object as gibbs_dm(H, T, sector_of=...), minus the embedding back into the
    full 2^L space, so it can be compared with the sector density matrices evolved
    here."""
    ev, U = np.linalg.eigh(H_sec.toarray() if sp.issparse(H_sec) else H_sec)
    w = np.exp(-(ev - ev.min()) / T)                 # shift for numerical stability
    return (U * (w / w.sum())) @ U.conj().T


def fidelity_to(target):
    """F(., target) as a closure, with the TARGET's square root computed once.

    uhlmann_fidelity(rho, target) re-derives sqrt(target) on every call; along a
    trajectory the target never changes, so hoisting it out halves the eigh work at
    each of the few hundred sampled times."""
    S = _sqrtm_psd(target)

    def F(rho):
        M = _sqrtm_psd(rho) @ S
        return float(np.clip(np.linalg.svd(M, compute_uv=False).sum(), 0.0, 1.0))
    return F


def lindblad_rhs(H_sec, L_sec):
    """Closure evaluating drho/dt = -i[H, rho] + sum_k (L_k rho L_k^d - {L_k^d L_k, rho}/2).

    Written with the non-Hermitian effective Hamiltonian

        K = -i H - (1/2) sum_k L_k^dag L_k   ->   drho/dt = K rho + rho K^dag
                                                            + sum_k L_k rho L_k^dag,

    which folds the whole anticommutator into one matrix and halves the number of
    products (2 + 2m instead of 2 + 4m). Sparse operators against a dense rho, so each
    product costs nnz * d_sec. This is the only place the generator is applied, and it
    is applied to a STATE -- never assembled as a d_sec^2 x d_sec^2 matrix."""
    Ldag = [Lk.conj().T.tocsr() for Lk in L_sec]
    K = (-1j * H_sec - 0.5 * sum(Ld @ Lk for Ld, Lk in zip(Ldag, L_sec))).tocsr()
    Kdag = K.conj().T.tocsr()

    def rhs(rho):
        out = K @ rho + rho @ Kdag
        for Lk, Ld in zip(L_sec, Ldag):
            out = out + Lk @ rho @ Ld
        return out
    return rhs


def rk4_dt(H_sec, safety=0.9):
    """Explicit-RK4 step size. The generator's fastest scale is set by ||H||, so scale
    the step with it; the electric term grows with L, hence the step must shrink."""
    return safety / max(float(spla.norm(H_sec, np.inf)), 1.0)


def _rk4_stepper(rhs, dt):
    def step(rho):
        k1 = rhs(rho)
        k2 = rhs(rho + 0.5 * dt * k1)
        k3 = rhs(rho + 0.5 * dt * k2)
        k4 = rhs(rho + dt * k3)
        return rho + (dt / 6.0) * (k1 + 2 * k2 + 2 * k3 + k4)
    return step


def basis_rho(init_state, idx, d):
    """|s><s| as a d_sec x d_sec matrix, given the sector's index list."""
    full = int(init_state, 2) if isinstance(init_state, str) else int(init_state)
    hit = np.where(idx == full)[0]
    if hit.size == 0:
        raise ValueError(f"{init_state!r} does not lie in this charge sector.")
    rho0 = np.zeros((d, d), dtype=complex)
    rho0[int(hit[0]), int(hit[0])] = 1.0
    return rho0


def exact_fidelity_curve(H_sec, L_sec, init_state, idx, T, dt=None, sample_dt=0.25,
                         infid_floor=1e-4, t_cap=4000.0):
    """F(rho(t), sector Gibbs) vs physical time, from a computational-basis start.

    One RK4 pass, recording F every `sample_dt`, and stopping as soon as either

      * 1 - F <= infid_floor          -- deep enough for the strictest target asked, or
      * the infidelity stops falling  -- the dynamics can get no closer than this.

    `infid_floor` is therefore the knob that sets the cost: it must sit below
    1 - max(F_TARGETS), and lowering it further only buys thresholds nobody reads.
    `sample_dt` is the spacing of the recorded points and so the raw resolution of
    every threshold time read off them -- t_at_fidelity interpolates between samples,
    which is well founded because the tail of 1 - F is exponential in t.

    No rho_ss hunt here (unlike the trace-distance version of this measurement): the
    target is the sector Gibbs state itself, and the returned ceiling reports how close
    the dynamics actually gets to it, so a target above that ceiling is caught rather
    than silently missed.

    Returns (ts, Fs, dt_rk4, ceiling) with ceiling = 1 - max(F) reached.
    """
    d = H_sec.shape[0]
    rho0 = basis_rho(init_state, idx, d)
    dt = rk4_dt(H_sec) if dt is None else dt
    step = _rk4_stepper(lindblad_rhs(H_sec, L_sec), dt)
    fine = max(1, int(round(sample_dt / dt)))
    F = fidelity_to(gibbs_sector(H_sec, T))

    rho, t = rho0.copy(), 0.0
    ts, Fs = [0.0], [F(rho0)]
    while t < t_cap:
        for _ in range(fine):
            rho = step(rho)
        t += fine * dt
        ts.append(t)
        Fs.append(F(rho))
        infid = 1.0 - Fs[-1]
        if infid <= infid_floor:
            break
        # plateau test: over the last 5 samples the infidelity fell by <0.1% of itself
        if t > 2.0 and len(Fs) > 6 and (Fs[-1] - Fs[-6]) <= 1e-3 * infid:
            break
    Fs = np.array(Fs)
    return np.array(ts), Fs, dt, float(1.0 - Fs.max())


def t_at_fidelity(ts, Fs, F_target):
    """First time F >= F_target AND stays there, interpolated between samples.

    Interpolation is linear in log(1 - F) against t, not in F: the approach to the
    fixed point is exponential, so the infidelity is log-linear in t and this is the
    interpolation that respects the curve's actual shape. Returns None if the
    trajectory never reaches F_target (i.e. the target is below the ceiling)."""
    ts, Fs = np.asarray(ts, dtype=float), np.asarray(Fs, dtype=float)
    k = next((i for i in range(len(ts)) if (Fs[i:] >= F_target).all()), None)
    if k is None:
        return None
    if k == 0:
        return 0.0
    y0, y1 = np.log(max(1.0 - Fs[k - 1], 1e-300)), np.log(max(1.0 - Fs[k], 1e-300))
    yt = np.log(max(1.0 - F_target, 1e-300))
    if not (y0 > y1):                                # flat or non-monotone: no interp
        return float(ts[k])
    w = float(np.clip((y0 - yt) / (y0 - y1), 0.0, 1.0))
    return float(ts[k - 1] + w * (ts[k] - ts[k - 1]))


def fit_scaling(x, y):
    """Fit y = A x^p and y = A e^{cx}; return both with their log-space R^2."""
    x, y = np.asarray(x, dtype=float), np.asarray(y, dtype=float)
    ly = np.log(y)
    out = {}
    for name, xv in (("power", np.log(x)), ("exponential", x)):
        s, i = np.polyfit(xv, ly, 1)
        ss_res = float(((ly - (s * xv + i)) ** 2).sum())
        ss_tot = float(((ly - ly.mean()) ** 2).sum())
        out[name] = (s, float(np.exp(i)), 1.0 - ss_res / ss_tot if ss_tot > 0 else 0.0)
    return out
